### ISSUE TITLE
Don't show image preview when open inside neovim

### ISSUE THREAD

**Issue by minhtien3297** [mikavilpas/yazi.nvim#112]
When opened inside neovim, the image preview just doesn't work

![Screenshot 2024-06-12 at 3 52 49 PM](https://github.com/mikavilpas/yazi.nvim/assets/66081361/8b421475-b4ca-41e3-a9b9-8e011d881536)

This is when open outside of neovim 

![Screenshot 2024-06-12 at 3 51 42 PM](https://github.com/mikavilpas/yazi.nvim/assets/66081361/3d407759-33af-4c27-bb07-f22f8651dadc)

**Comment by mikavilpas** [comment]
I have this issue myself. I looked into it a while ago and I think this is not supported in neovim's embedded terminal yet.

I don't know if this can be resolved until support is added. Let's keep this open to track the status as well as any additional findings and ideas.

**Comment by daUnknownCoder** [comment]
@mikavilpas buddy check this out: https://new.reddit.com/r/neovim/comments/1dcjuxc/simplyfilenvim_now_can_use_3rdimagenvim_to/

**Comment by mikavilpas** [comment]
Ok, nice find - that was fast 😄 ! I think that might work nicely, but one issue remains: in neovim, we don't yet know
what is being previewed in yazi.

This is actually a neovim specific limitation and can be worked around with e.g. my proposal at
https://github.com/sxyazi/yazi/pull/1004, which would add the ability to read events from the embedded yazi process in
real time. Currently we can only read them after yazi has closed.

So it would work like this:

```mermaid
sequenceDiagram
  neovim->>yazi: open yazi
  yazi->>neovim: file hovered event: /path/to/image.png
  neovim-->neovim: preview image
  yazi->>neovim: file hovered event: /path/to/file.txt
  neovim-->neovim: 🔎 not an image, don't preview anything
```

**Comment by mikavilpas** [comment]
I also wonder if this would work if yazi were configured to use https://github.com/jstkdng/ueberzugpp with yazi. I haven't tried this out, so it might be subject to the same neovim terminal limitation which causes images not to show.

**Comment by daUnknownCoder** [comment]
> we don't yet know what is being previewed in yazi.

we can check the filetype? restrict the config to `jpg`, `png`, ...

**Comment by mikavilpas** [comment]
The issue is not yet knowing the name of the file that is hovered in yazi.

**Comment by daUnknownCoder** [comment]
> I also wonder if this would work if yazi were configured to use https://github.com/jstkdng/ueberzugpp with yazi. I haven't tried this out, so it might be subject to the same neovim terminal limitation which causes images not to show.

https://yazi-rs.github.io/docs/configuration/yazi/#preview.ueberzug_scale

**Comment by mikavilpas** [comment]
Want to do an experiment with yazi + ueberzugpp + yazi.nvim to see if it works with this configuration? 🙂

**Comment by daUnknownCoder** [comment]
> Want to do an experiment with yazi + ueberzugpp + yazi.nvim to see if it works with this configuration? 🙂

wait what? it already works there's no need for anything to be done 🙃, i havent updated, i dont use `image.nvim` 

> [!IMPORTANT]
we have to pass something to the main config of yazi for the ueberzug offset (`~/.config/yazi/yazi.toml`)
```toml
[preview]
ueberzug_offset = [7.5,1,0,0]
```
> [!IMPORTANT]
this ⬆️ is what i configured for correct display of image, and it might be different for different people, as u might see the below images, the ueberzug offset is messed up ...


```lua
opts = {
    floating_window_scaling_factor = 1,
}
```
![image](https://github.com/mikavilpas/yazi.nvim/assets/84800625/e11044cd-a438-45cd-93b7-88d139039176)

```lua
opts = {
    floating_window_scaling_factor = 0.8,
}
```
![image](https://github.com/mikavilpas/yazi.nvim/assets/84800625/cc73cac3-6198-443a-a78b-70bdb2e72292)

direct yazi window:
![image](https://github.com/mikavilpas/yazi.nvim/assets/84800625/426200e6-585a-406c-8572-aa867543dbab)

**Comment by mikavilpas** [comment]
Oh, nice! Excellent work!

**Comment by daUnknownCoder** [comment]
> Oh, nice! Excellent work!

ok i didnt do anything, my ueberzug wasnt working (i hadnt updated it for a while) :p

**Comment by sxyazi** [comment]
Regarding Yazi's behavior in Neovim: https://yazi-rs.github.io/docs/image-preview#neovim

**Comment by mikavilpas** [comment]
Awesome - thanks for the link!

**Comment by piersolenski** [comment]
Is this possible with what was suggested in https://github.com/mikavilpas/yazi.nvim/issues/762?
