### ISSUE TITLE
Support systems with nushell as the default shell

### ISSUE THREAD

**Issue by benjamin-voisin** [mikavilpas/yazi.nvim#130]
I'm using neovim v0.10.0 and Yazi v0.2.5 on arch. I copied the install script on the Readme for Lazy.
When I try to launch yazi (with <leader>- or <leader>cw), the floating window appears but shows this error :
```
error: unexpected argument '>' found

Usage: yazi [OPTIONS] [ENTRY]

For more information, try '--help'.

[Process exited 2]
```

**Comment by benjamin-voisin** [comment]
I get this :
```
[2024-06-24 17:17:07] DEBUG Opening yazi with the command: (yazi '/home/binj/Documents/file.txt' --local-events "rename,delete,trash,move,cd" --chooser-file "/tmp/nvim.binj/S177ju/0" > "/tmp/nvim.binj/S177ju/1")
```
And it doesn't launch in my shell. I'm quite sure that this is because I use [nushell](https://github.com/nushell/nushell) (and the `>` operator is not as in bash).
The command without the redirection : 
```
yazi '/home/binj/Documents/file.txt' --local-events "rename,delete,trash,move,cd" --chooser-file "/tmp/nvim.binj/S177ju/0"
```
works in my shell without issues

**Comment by mikavilpas** [comment]
Okay, sounds like good progress. How have you set your neovim to use nushell?

What does nushell use for redirecting output to a file?

**Comment by benjamin-voisin** [comment]
Nushell is my default shell for my whole user, so nvim uses it. After some tries, here is the working command to reproduce the same comportment:
```
yazi '/home/binj/Documents/file.txt' --local-events "rename,delete,trash,move,cd" --chooser-file "/tmp/nvim.binj/S177ju/0" out> "/tmp/nvim.binj/S177ju/1"
```
(It's juste `out>` instead of `>`)

I'm looking at ways to easily know which shell we are using, but I don't find anything very satisfying. Something like `echo $SHELL` but ofc in nushell it's `echo $env.SHELL`...

**Comment by mikavilpas** [comment]
I don't know how well supported nushell is is neovim. I googled around for a bit and sadly found almost no results.

There is `:shellredir`

```text
						*'shellredir'* *'srr'*
'shellredir' 'srr'	string	(default ">", ">&" or ">%s 2>&1")
			global
	String to be used to put the output of a filter command in a temporary
	file.  See also |:!|.  See |option-backslash| about including spaces
	and backslashes.
	The name of the temporary file can be represented by "%s" if necessary
	(the file name is appended automatically if no %s appears in the value
	of this option).
	The default is ">".  For Unix, if the 'shell' option is "csh" or
	"tcsh" during initializations, the default becomes ">&".  If the
	'shell' option is "sh", "ksh", "mksh", "pdksh", "zsh", "zsh-beta",
	"bash" or "fish", the default becomes ">%s 2>&1".  This means that
	stderr is also included.  For Win32, the Unix checks are done and
	additionally "cmd" is checked for, which makes the default ">%s 2>&1".
	Also, the same names with ".exe" appended are checked for.
	The initialization of this option is done after reading the vimrc
	and the other initializations, so that when the 'shell' option is set
	there, the 'shellredir' option changes automatically unless it was
	explicitly set before.
	In the future pipes may be used for filtering and this option will
	become obsolete (at least for Unix).
	This option cannot be set from a |modeline| or in the |sandbox|, for
	security reasons.
```

But this looks pretty confusing. In yazi's case both output streams (stdout and stderr) are needed separately, and this option seems to mix them into one in some cases. I don't feel comfortable using it as it doesn't give a guarantee of not breaking for some users.

It might be a good idea to change your neovim to use a traditional shell by default, and enable nushell for specific use cases that you care about. I don't know how this can be done.

**Comment by mikavilpas** [comment]
I have an upcoming feature that might solve this. It gets rid of the problematic shell redirection logic entirely.

If you're willing to install `yazi` and `ya` from the currently latest source, you can try it out in https://github.com/mikavilpas/yazi.nvim/pull/152

**Comment by mikavilpas** [comment]
Wow that's great 👍🏻👍🏻 

I'm planning to merge that in this week, and will close this when that happens.

**Comment by Ben-PH** [comment]
I reinstalled yazi using `cargo install --locked --git ...

While it was in the process of doing that, I reinstalled the nvim plugin, and got a "please install yazi" error as expected.

Once the install was done, I tried rerunning it and still got the same `unexpected argument` error pop up, but when I uncommented these lines in the config:

```
    -- enable these if you are using the latest version of yazi
    use_ya_for_events_reading = true,
    use_yazi_client_id_flag = true,
```

...it worked!

Hopefully the next person recreating my journey will scroll down to here and save themselves a touch of headache.

**Comment by mikavilpas** [comment]
Good stuff - glad you got it working. This will likely be the default behaviour once the next stable version of yazi comes out.

Right now we have to do this so everyone is not forced to install from source.
