### ISSUE TITLE
Is the hacky mouse support still needed?

### ISSUE THREAD

**Issue by mikavilpas** [mikavilpas/yazi.nvim#176]
Some time ago we hacked together a solution for using the scrollwheel to scroll the selected file up and down. After that, yazi actually landed its own mouse support that is also able to scroll the preview pane (the contents of the selected file on the right) https://github.com/mikavilpas/yazi.nvim/issues/49#issuecomment-2144500458

@zeioth I was wondering if the hacky mouse support is still a useful feature, or maybe it should be deprecated and eventually removed. Are you still using it?

**Comment by Zeioth** [comment]
@mikavilpas it is still necessary yes. That fix is for the neovim terminal, not for Yazi itself. ATM neovim don't really support mouse out the box on the terminal without this trick.

**Comment by mikavilpas** [comment]
Ok, let's keep it in then. Thanks for checking!
