### ISSUE TITLE
Support non-Posix shells

### ISSUE THREAD

**Issue by mrdgo** [mikavilpas/yazi.nvim#181]
I use nushell. It doesn't support the syntax `command > file`. When I start yazi from neovim, I get `error: unexpected argument '>' found`. I see two options:
1. Add an option to this plugin to manually override the shell used to launch yazi (probably the easiest)
2. Add shell detection and support a variety of non-posix shells (nushell, elvish, fish, etc.)

Regarding 1., I currently hack it like this:
```lua
		{
			"<leader>y",
			function()
				vim.o.shell = "/usr/bin/sh"
				require("yazi").yazi()
				vim.o.shell = "/usr/bin/nu"
			end,
			desc = "Open the file manager",
                }
```

**Comment by mikavilpas** [comment]
Someone else also had this issue and they reported it was solved using this:

https://github.com/mikavilpas/yazi.nvim/issues/130#issuecomment-2212512487

Could you try that out? You will need to install the latest yazi, see the instructions for more info.

**Comment by mrdgo** [comment]
Erm, I don't understand what to do there. Could you elaborate for a dummy, please? :innocent:

**Comment by mikavilpas** [comment]
That's right - although you also need to have the latest `yazi` and `ya` installed. You can run `:checkhealth yazi` to check everything is okay.

But if it already works, it's probably all good 😄
