### ISSUE TITLE
Unable to use yazi.nvim - Path not found

### ISSUE THREAD

**Issue by AnirudhG07** [mikavilpas/yazi.nvim#210]
Hi, I just downloaded yazi.nvim but it doesn't work. The issue shows PATH not found.

## Configs
Neovim v10.0
Yazi version- build from source (just before UI breaking changes)

## Checkhealth yazi
```
yazi: require("yazi.health").check()

yazi ~
- Running yazi.nvim version 2.2.0
- WARNING yazi not found on PATH
- WARNING yazi --version looks unexpected, saw zsh:1: command not found: yazi
  
- ERROR Failed to run healthcheck for "yazi" plugin. Exception:
  ...lar/neovim/0.10.0/share/nvim/runtime/lua/vim/version.lua:174: attempt to index local 'version' (a nil value)
  
```

My yazi.lua-
```
---@type LazySpec
return {
  "mikavilpas/yazi.nvim",
  event = "VeryLazy",
  keys = {
    -- 👇 in this section, choose your own keymappings!
    {
      "<leader>yz",
      function()
        require("yazi").yazi()
      end,
      desc = "Open the file manager",
    },
    {
      -- Open in the current working directory
      "<leader>cw",
      function()
        require("yazi").yazi(nil, vim.fn.getcwd())
      end,
      desc = "Open the file manager in nvim's working directory" ,
    },
  },
  ---@type YaziConfig
  opts = {
    -- if you want to open yazi instead of netrw, see below for more info
    open_for_directories = false,
  },
}
```
Since I have build from source, I have made an alias in my zshrc, which is
```
alias yazi='bash -ic "source /dev/stdin; /Users/anirudhgupta/yazi/target/release/yazi $@"'
```
This works nicely for yazi inside terminal, but I donno if this is the issue or what. 

Please suggest a fix to solving it.

**Comment by mikavilpas** [comment]
Looks like `yazi` is not on your PATH environment variable. Try to add `~/.cargo/bin` to your PATH. For me, yazi can be found here:

```sh
$ which yazi
/Users/mikavilpas/.cargo/bin/yazi
```

To build yazi from source, I run these commands in the yazi git repository:

<img width="382" alt="image" src="https://github.com/user-attachments/assets/65473f51-4f53-4da2-b179-31a20530e99f">

**Comment by AnirudhG07** [comment]
Thanks that worked perfectly. Thanks so much!
