### ISSUE TITLE
yazi is still loaded by default in 3.1.5

### ISSUE THREAD

**Issue by rick-yao** [mikavilpas/yazi.nvim#266]
According to #253 , yazi should not be loaded by default. But in my config, it is still loaded.
Below is my config. My yazi.nvim verison is 3.1.5.
```lua
---@type LazySpec
return {
  "mikavilpas/yazi.nvim",
  event = "VeryLazy",
  keys = {
    -- 👇 in this section, choose your own keymappings!
    {
      "<leader>-",
      function() require("yazi").yazi() end,
      desc = "Open the file manager",
    },
    {
      -- Open in the current working directory
      "<leader>+",
      function() require("yazi").yazi(nil, vim.fn.getcwd()) end,
      desc = "Open the file manager in nvim's working directory",
    },
  },
  ---@type YaziConfig
  opts = {
    open_for_directories = false,
  },
}
```

**Comment by mikavilpas** [comment]
Hi! It's possible to lazy load yazi.nvim if you remove `event = "VeryLazy"` in your lazy.nvim spec. It will work if you don't want to use `open_for_directories = true` (like you have configured).

Could you try that out and see if it works for you?

**Comment by rick-yao** [comment]
Thanks, it works!
