### ISSUE TITLE
Unexpected argument '--local-events' found

### ISSUE THREAD

**Issue by I-Own-You** [mikavilpas/yazi.nvim#29]
Hi, just found your plugin <a href="https://dotfyle.com/plugins/mikavilpas/yazi.nvim"> here </a>
Installed with **`lazy.nvim`**, tried to use it, but encountered an **`error`**.
<hr>

Here is the **`error`:**
![image](https://github.com/mikavilpas/yazi.nvim/assets/91146968/f6d47336-8c0a-4989-8edf-2e945a8de10e)

**Comment by sxyazi** [comment]
Hi, this plugin requires the latest Yazi code at the moment.

**Comment by I-Own-You** [comment]
I already have the latest version, as for <a href="https://aur.archlinux.org/packages/yazi-git">2024-03-10 09:23 UTC</a> from the core package of `arch system`.
the `git version` is 5 days younger <a href="https://archlinux.org/packages/extra/x86_64/yazi/">2024-03-05 13:46 (UTC)</a>
<hr>

Am i missing something ?

**Comment by mikavilpas** [comment]
Hi, I think you maybe have the latest release of yazi, but it looks like this plugin currently works with the latest unreleased version..

I see a couple of options:
- I can make the event handling optional so that we can avoid this error for older versions of yazi. In the future I want to support newer versions only, but I think right now it need
- in the mean time you can build yazi from source

**Comment by I-Own-You** [comment]
i did build and install it from source now, but the keybindings doesnt seem to work, like opening files, or opening in split, .etc

**Comment by mikavilpas** [comment]
@I-Own-You can you show what `yazi --version` outputs for you?

Mine is `Yazi 0.2.4 (3881341 2024-04-10)`

Can you also show what your neovim config is for yazi?

**Comment by I-Own-You** [comment]
My version is: `Yazi 0.2.4 (9e75ed5 2024-04-16)`

the config is the default one.

**Comment by mikavilpas** [comment]
Thanks, I'll try to do some investigation later today. Also, what is your neovim version?

I am running

```
NVIM v0.10.0-dev-2915+g57adf8c6e
Build type: Release
LuaJIT 2.1.1710088188
Run "nvim -V1 -v" for more info
```

**Comment by I-Own-You** [comment]
Mine is:

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

**Comment by I-Own-You** [comment]
I have problems with nvim latest git version like 0.10.x, it randomly crashes, but i will try to install it, maybe it will work with yazi

**Comment by I-Own-You** [comment]
I have installed the latest neovim git version, didnt work anyway, sadly

**Comment by mikavilpas** [comment]
Ok, I see some problems that might be easily fixable. If you are still using what seems to be your config, it seems like you're actually overriding the default keymappings with an empty function [here](https://github.com/I-Own-You/nvim/commit/d3e2e0ab96bf3330c123ecbbb87cbc1ddb87cbe8#diff-f67aedec5a7aa2a91d70f19e84298557060b7086f340102cc7b36e439664c4e4R32).

Can you try using a very minimal set of options, for example the same ones that I set in my config [here](https://github.com/mikavilpas/dotfiles/blob/ddf917fd326c4a1832e123e255cf56a167566282/.config/nvim/lua/plugins/my-file-manager.lua?plain=1#L1)?

---

I think this confusion is a failure of communication on my part. I will try to make the readme much clearer about this 👍🏻

**Comment by I-Own-You** [comment]
> Ok, I see some problems that might be easily fixable. If you are still using what seems to be your config, it seems like you're actually overriding the default keymappings with an empty function [here](https://github.com/I-Own-You/nvim/commit/d3e2e0ab96bf3330c123ecbbb87cbc1ddb87cbe8#diff-f67aedec5a7aa2a91d70f19e84298557060b7086f340102cc7b36e439664c4e4R32).
> 
> Can you try using a very minimal set of options, ~for example the same ones that I set in my config [here](https://github.com/mikavilpas/dotfiles/blob/ddf917fd326c4a1832e123e255cf56a167566282/.config/nvim/lua/plugins/my-file-manager.lua?plain=1#L1)~?
> 
> update: I added the instructions to the readme now
> 
> I think this confusion is a failure of communication on my part. I will try to make the readme much clearer about this 👍🏻

indeed, these 2 lines are the problem:

for opening functionality like "o":  `open_file_function = function(chosen_file, config) end`
for keymaps: 	`set_keymappings_function = function(yazi_buffer_id, config) end`

so i commented them, now it works fine

**Comment by mikavilpas** [comment]
Nice 👍🏻 

Does it work for you now? Can this issue be closed?

**Comment by I-Own-You** [comment]
> Nice 👍🏻
> 
> Does it work for you now? Can this issue be closed?

actually, one more question if you dont mind, there is `o` that will open the file, but there is `O` for interactive opening from choosing programms, it doesnt work in yazi from neovim, its supposed to work like that ?

**Comment by mikavilpas** [comment]
I hadn't realized that's a feature 😆 

No, it's not supposed to work that way. I'll investigate, thanks for the report.

**Comment by I-Own-You** [comment]
> I hadn't realized that's a feature 😆
> 
> No, it's not supposed to work that way. I'll investigate, thanks for the report.

then yes, this issue can be closed

**Comment by mikavilpas** [comment]
Ok, I'll track that in the linked issue. You can subscribe to that for updates.
