### ISSUE TITLE
Pressing ESC has a very high delay

### ISSUE THREAD

**Issue by Zeioth** [mikavilpas/yazi.nvim#295]
## Issue
Pressing ESC when inside yazi, takes 1s to refresh the screen.

## How to reproduce
* Open any dialog inside yazi, for example 'rename file'. 
* Press `ESC`.
* The window will take 1s to actually close.

## Possible solution
I imagine this happen because of performance reasons. If so it would be nice to give users an options to configure this.

**Comment by mikavilpas** [comment]
Can you follow these instructions 

https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md

I have a hunch about what this might be related to, but I'd like to see if you can reproduce this, and read any logs.

**Comment by Zeioth** [comment]
@mikavilpas I found time to test. I can repro the issue on the minfile you provide:
![screenshot_2024-08-02_17-51-09_189951430](https://github.com/user-attachments/assets/13b68fb8-c74d-46f6-815b-83c0962fd1cc)

And this is the generated log:
![screenshot_2024-08-02_17-49-32_431705085](https://github.com/user-attachments/assets/866fceb0-a4c2-41ce-a676-dbfbb634c8e9)

I've also recorded a youtube video so you can appreciate it better:
* https://www.youtube.com/watch?v=GsQD2agOtGQ&feature=youtu.be

## More info
* OS: Arch linux
* Terminal: [foot version: 1.17.2 +pgo +ime +graphemes -assertions](https://codeberg.org/dnkl/foot)

**Comment by mikavilpas** [comment]
Wow that's really great, thanks for the detailed reproduction! I am on vacation right now but I will look into it in hopefully a few days.

I don't usually use this feature of yazi myself, so it may be possible that there is some slowness.

Also, your setup looks incredible, nice job with it! I miss Linux so much as I now use osx for my job...

**Comment by mikavilpas** [comment]
I was able to reproduce the issue, and I think I found the cause. It was a workaround for an old lazyvim issue, but it looks like that workaround is no longer needed. I removed it, and got a 1s speedup!

**Comment by Zeioth** [comment]
@mikavilpas I've tested the PR. It works correctly indeed!!

**Comment by mikavilpas** [comment]
Awesome, thanks for the verification. 👍🏻 👍🏻
