### ISSUE TITLE
How to open multiple buffers?

### ISSUE THREAD

**Issue by Zeioth** [mikavilpas/yazi.nvim#300]
Following the readme I've implemented:

```lua
opts = {
  hooks = {
    yazi_opened_multiple_files = function(chosen_files, config, state)
      -- Iterate over the selected files
      for _, file in ipairs(chosen_files) do
        -- Open each file in a new buffer
        vim.api.nvim_command("e " .. file)
      end
    end,
  },
}
```

But after selecting multiple files in visual mode in yazi and pressing `ENTER`, only one buffer is opened. 

![screenshot_2024-07-31_17-11-16_085115742](https://github.com/user-attachments/assets/bf1d873b-b42c-4c9e-8dc0-be19a224dbc9)
![screenshot_2024-07-31_17-11-26_932717970](https://github.com/user-attachments/assets/9c6ce13c-18a2-47d6-978f-070313d6853e)

I'm missing something?

**Comment by Zeioth** [comment]
The next prints nothing
```lua
print(vim.inspect(chosen_files))
```

**Comment by mikavilpas** [comment]
With this reproduction script it works for me. Can you try it out?

```lua
-- You can use this file to reproduce an issue with your configuration.

---@module "yazi"
---@module "lazy"

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)
vim.g.mapleader = ' '

-- install the following plugins
---@type LazySpec
local plugins = {
  'folke/tokyonight.nvim',
  {
    'mikavilpas/yazi.nvim',
    event = 'VeryLazy',
    keys = {
      {
        '<leader>fy',
        function()
          require('yazi').yazi()
        end,
      },
    },
    ---@type YaziConfig
    opts = {
      open_for_directories = true,
      ---@diagnostic disable-next-line: missing-fields
      hooks = {
        yazi_opened_multiple_files = function(chosen_files)
          vim.notify('Opening ' .. #chosen_files .. ' files')
          for _, file in ipairs(chosen_files) do
            vim.api.nvim_command('e ' .. file)
          end
        end,
      },
    },
  },
}
require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

vim.cmd.colorscheme('tokyonight')
-- add anything else here
```


https://github.com/user-attachments/assets/bcc5a33c-ba58-4258-9229-6c1e296332ee

**Comment by Zeioth** [comment]
Your repro file works as expected. I'm gonna research and document what is interfering on this issue once I find it 👍

**Comment by Zeioth** [comment]
[mikavilpas](https://github.com/mikavilpas) I found the issue:

It was not an issue in my config. It happens when the user overrides the `ENTER` key on `~/.config/keymap.toml`.

In my case I had
```
# Plugin: smart-enter
# ==============================================================================
[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"
```

so after deleting that, it works as expected.

**Comment by Zeioth** [comment]
@xfzv I'm glad that's the case on your end, but it's confirmed by the author: https://github.com/sxyazi/yazi/issues/1378

* It's not an issue per se, they've intentionally decided to disable support for opening multiple files with smart-enter by default.
* This only affect smart-enter. If you don't use it you can open multiple files at the same time without problem.
* You can also leave the options empty, you don't have to set it to false. Just don't set it to true.

```lua
ya.manager_emit(h and h.cha.is_dir and "enter" or "open", { })
```
