### ISSUE TITLE
It seems yazi plugin installs bufferline but no mention in the readme… is this expected?

### ISSUE THREAD

**Issue by GitMurf** [mikavilpas/yazi.nvim#306]
Is buffer line being installed by this plugin?

If so, what is it used for? I use a different tab / buffer manager and am afraid of conflicts.

Also, if it is indeed required then I would suggest adding to readme and also adding as a dependency in the plugin config so users realize bufferline must be installed with this plugin.

Thanks!

**Comment by mikavilpas** [comment]
Hi, thanks for the question and idea! Bufferline is indeed a dependency, and you can find what it's used for here https://github.com/mikavilpas/yazi.nvim/pull/194

The entire plugin is not loaded. Actually only a single file is loaded if the color functionality is needed, so I think the chance for any conflicts is very low in this case.

If you're curious, you can read the implementation as it's quite minimal https://github.com/search?q=repo%3Amikavilpas%2Fyazi.nvim+bufferline&type=code

The dependency itself only needs to be added manually if the user doesn't use a modern package manager. In the case of lazy.nvim it's a relatively recent feature but it's well documented here https://lazy.folke.io/packages

I think what the community is going towards is actually not having users declare dependencies manually as there seem to be three different ways to do this right now (on the lazy.nvim documentation page I linked).

...but I think your idea is good, and maybe I should add an explanation to the readme to make this clearer 🙂

**Comment by GitMurf** [comment]
@mikavilpas thanks for the explanation! That all makes sense. I am just kind of OCD about how many plugins I install and what / why plugins get added in my config ;)

I think as you mentioned, just a small little blurb would be helpful so that people don't spend time wondering why another plugin was added without explicitly defining it and without mention in the readme.

And now you have this great gh issue you can link to for details haha ;)

Thanks for the great work on the plugin!

**Comment by GitMurf** [comment]
@mikavilpas the updates of readme look great. Just what I was envisioning. Thanks!
