### ISSUE TITLE
<c-s> doesnt respect the state

### ISSUE THREAD

**Issue by I-Own-You** [mikavilpas/yazi.nvim#31]
in keymaps of the yazi there is: `<C-s>           search none                  Cancel the ongoing search`

this means it will remove the previous searched items with eiter `s` or `S` , but it behaves like splitting the file.

**Comment by I-Own-You** [comment]
i mean a good options is to just change from <c-s> to <c-x> as other plugins do often, like [FzfLua](https://github.com/ibhagwan/fzf-lua) does, so you wont interfere with yazi default keymaps

**Comment by mikavilpas** [comment]
Hmm I see. I think that sounds good. Do you have a suggestion for a better keymap?

**Comment by I-Own-You** [comment]
> i mean a good options is to just change from < c-s > to < c-x > as other plugins do often, like [FzfLua](https://github.com/ibhagwan/fzf-lua) does, so you wont interfere with yazi default keymaps

@mikavilpas

**Comment by mikavilpas** [comment]
oh sorry I didn't see your new post. I'll try changing the default keymap.
