### ISSUE TITLE
Wrong color for `ya.group_name`

### ISSUE THREAD

**Issue by xfzv** [mikavilpas/yazi.nvim#326]
```console
% yazi -V
Yazi 0.3.0 (cc50f94 2024-08-05)
```

I'm using a custom status bar in `~/.config/yazi/init.lua`:

```lua
function Status:owner()
  local h = cx.active.current.hovered
  if not h or not ya.user_name then
    return ui.Line({})
  end
  return ui.Line({
    ui.Span(ya.user_name(h.cha.uid) or tostring(h.cha.uid)):fg("green"),
    ui.Span(":"),
    ui.Span(ya.group_name(h.cha.gid) or tostring(h.cha.gid)):fg("magenta"),
    ui.Span(" "),
  })
end
```

This is how my ownership section looks in `yazi`:
![yazi](https://github.com/user-attachments/assets/f55dc081-b728-4c43-8332-f7541be956e2)

This is how it looks in `yazi.nvim`:
![yazi-nvim](https://github.com/user-attachments/assets/6e87daf7-c6c7-434e-88f0-e579b2eab8a0)

`root` (group owner) is using `#f5c2e7` (`pink`) instead of `#b4befe` (my override for `lavender`)

All the other colors seem to respect my color scheme (Catppuccin mocha) just fine.

**Comment by mikavilpas** [comment]
Hmm I suspect Neovim might change the color. Does the color appear correctly if you open :term and then open yazi in it?

Yazi.nvim doesn't change the colors as far as I know.

**Comment by mikavilpas** [comment]
Hmm that is quite interesting. I might have the same behaviour as I use catppuccin macchiato as my theme, but on the other hand I don't have a custom component like you (I think) 🤔 

I'm not sure how the neovim colors affect the terminal theme (I thought this would not happen, to be honest), but as far as I know it's not related to this plugin.

If you open an issue in https://github.com/catppuccin/nvim for example, would you mind linking this issue? I would like to follow that to see if there is a workaround for this behaviour.

**Comment by mikavilpas** [comment]
Sure, here is a screenshot:

![image](https://github.com/user-attachments/assets/ad5f3b9f-0a76-4a2c-96d5-d96ec83884f1)

I issued `:Catppuccin mocha` and opened yazi, the `/Users/mikavilpas/dotfiles/.config/yazi/init.lua` file set to the contents you sent in your previous message.

**Comment by mikavilpas** [comment]
Hmm yeah, I have seen the same behaviour when testing. For most testing it's actually desirable, but I can see how it doesn't help much here.

Can you try the following:

```lua
-- You can use this file to reproduce an issue with your configuration.

---@module "yazi"
---@module "lazy"

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- copy yazi config to .repro/config/yazi
local yazi_dir = root .. '/config/yazi'
vim.uv.fs_symlink(vim.fn.expand('~/.config/yazi'), yazi_dir, {}, function(err)
  if err then
    print('Error creating symlink:', err)
  end
end)

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)
vim.g.mapleader = ' '

-- install the following plugins
---@type LazySpec
local plugins = {
  'folke/tokyonight.nvim',
  {
    'mikavilpas/yazi.nvim',
    event = 'VeryLazy',
    keys = {
      {
        -- 👇 choose your own keymapping
        '<leader>fy',
        function()
          require('yazi').yazi()
        end,

        { desc = 'Open the file manager' },
      },
    },
    ---@type YaziConfig
    opts = {
      open_for_directories = false,
    },
  },
}
require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

vim.cmd.colorscheme('tokyonight')
-- add anything else here
```

This will create a symbolic link to the `.repro/config/` directory for yazi and should fix it. If there are any errors symlinking, you can issue `:messages` in neovim to see them.
