### ISSUE TITLE
Cant open Yazi (E492: Not an editor command: Yazi)

### ISSUE THREAD

**Issue by Shorkerrr** [mikavilpas/yazi.nvim#340]
As the title says, i cant seem to open an instance of Yazi in NeoVim, 

I am using Vim-Plug to install .vim and .nvim plugins. 
Running :checkhealth yazi returns:
yazi
- Running yazi.nvim version 5.1.1
- Found _yazi_ version _Yazi 0.3.0 (Arch Linux 2024-08-07)_
- yazi.nvim log file is at /home/user/.local/state/nvim/yazi.log
- hint: use _gf_ to open the file path under the cursor
- OK yazi

**Comment by mikavilpas** [comment]
To setup the commands you need to `require("yazi"). setup ()`. What does your config look like?

**Comment by Shorkerrr** [comment]
> To setup the commands you need to `require("yazi"). setup ()`. What does your config look like?

Where do i find this config? Is it within my NeoVim plugins or within my yazi config directory?
Im not fully sure what you really mean by this.

**Comment by mikavilpas** [comment]
What I mean is, what does your neovim config look like when it comes to yazi.nvim?

It might be that you are not calling `require("yazi").setup()`. This means the commands like `:Yazi` are not available, and to fix this you can either add the call, or use the lua api which will work even without `.setup()`.

For an example of the lua api, you can see my own config in the following commit: https://github.com/mikavilpas/dotfiles/commit/d3a23885ad755ceda8bbdcc7d33a4ac71dd57773

**Comment by Shorkerrr** [comment]
> For an example of the lua api, you can see my own config in the following commit: [mikavilpas/dotfiles@d3a2388](https://github.com/mikavilpas/dotfiles/commit/d3a23885ad755ceda8bbdcc7d33a4ac71dd57773)

Is this directory something created with lazy.nvim? I dont have anything like it in my .config/nvim. I find my plugin and all the code for it within .config/nvim/autoload/plugged/yazi.nvim/
_Tbh, its my mistake for simply following a youtube guide on how to setup some plugins for NeoVim without any actual knowledge.._

**Comment by mikavilpas** [comment]
Hehe, don't feel bad - I sometimes feel none of this makes any sense if I think about it long enough 😄 

I can probably help you set it up, but I don't know anything about vim-plug. Can you copy something into this reproduction file (it's okay if it doesn't work, I just need something to get started) https://github.com/mikavilpas/yazi.nvim/blob/main/repro.lua

There's some instructions on how to run that file here that will help you get started https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md

**Comment by Shorkerrr** [comment]
I dont have any config.lua (or similar file) that i can copy in to the repro.lua.

Im not sure how much of a help this screenshot would do, but i guess it gives some context to what i mean by that i dont have any actual config.lua file for NeoVim
![2024-08-08-205127_hyprshot](https://github.com/user-attachments/assets/77db5ecc-e12e-4839-bd88-0f88ffa567aa)

**Comment by mikavilpas** [comment]
Can you show the yazi.nvim file?

**Comment by mikavilpas** [comment]
Can you show me how you added yazi.nvim to your setup? How do you configure other plugins?
