### ISSUE TITLE
bug: opening multiple files in a directory containing space is broken

### ISSUE THREAD

**Issue by xfzv** [mikavilpas/yazi.nvim#346]
To reproduce

1. Create a directory named `foo_bar` with two or more let's say `markdown` files with some content in it
2. Copy `foo_bar` directory and rename it to `foo bar`
3. Use [`repro.lua`](https://raw.githubusercontent.com/mikavilpas/yazi.nvim/4e549120e1ff2702b6ea1eff3640a879fffb2141/repro.lua)
4. `nvim -u repro.lua`
5. Run `:Yazi`, go to `foo_bar` directory first
6. Select all files and press Enter
7. All files are correctly opened
8. Repeat with `foo bar` directory this time
9. All buffers are empty and the first one listed with `:buffers` is `/path/to/foo` (shouldn't be listed since `foo bar` is the directory, not a file)

---

Edit: the actual `:buffers` list with `foo bar` directory:

```
1 %a   "/tmp/foo"                     line 1
3      "bar/1.md"                     line 0
4      "bar/2.md"                     line 0
5      "bar/3.md"                     line 0
6      "bar/4.md"                     line 0
```

**Comment by mikavilpas** [comment]
This is indeed a bug, thanks for reporting.

It should be fixed with the PR linked above - can you try that out?
