### ISSUE TITLE
Toggle a persistent Yazi panel ?

### ISSUE THREAD

**Issue by uwla** [mikavilpas/yazi.nvim#358]
Hello thanks for the awesome plugin!

Is there a way to toggle an Yazi panel such that it persists the state after close? For example, I open an Yazi panel (may be at the current buffer directory or at the VCS root) and I navigate to a subdir, open some tabs, and so on, ..., and then I'd like to reopen that same Yazi panel instead of starting a fresh new one

**Comment by mikavilpas** [comment]
Hi, glad you're enjoying it! I think I'll add support for this in the future.

For now, you can try `:Yazi toggle` which is a "dumb" implementation. It simply reopens yazi where it was closed previously.

It's not perfect but in some cases it can be useful. Let's keep this open until a fancier solution is available 🙂

**Comment by chenxin-yan** [comment]
In shell, Yazi can be suspended with built in keymap `<c-z>`, and brought back with `fg` command. I will take a look latter, maybe we can find a way to integrate it with Yazi.nvim.
