### ISSUE TITLE
An unknown element "" was received

### ISSUE THREAD

**Issue by Daydreamer-riri** [mikavilpas/yazi.nvim#366]
Thank you for your great work! I encountered some issues while trying to use it.
It does not work properly on Windows.
```
yazi ~
- Running yazi.nvim version 5.5.0
- WARNING yazi --version looks unexpected, saw An unknown element "" was received. This can happen if the remote process closed or ended abnormally.
  
- ERROR Failed to run healthcheck for "yazi" plugin. Exception:
  ...gram Files/Neovim/share/nvim/runtime/lua/vim/version.lua:174: attempt to index local 'version' (a nil value)
```
  
![image](https://github.com/user-attachments/assets/dbd5d18b-ef48-4d97-8a57-d641a8e7933b)

![image](https://github.com/user-attachments/assets/60836f78-34c7-4ab0-87ec-10438f8f5cae)

**Comment by mikavilpas** [comment]
Hello! I don't use windows myself unfortunately, but it looks like the healthcheck fails to run because the following command fails:

```vim
:=vim.fn.system("yazi --version")
```

I bet to fix the issue, that command should succeed. It probably indicates something is wrong with your neovim setup on windows.

**Comment by mikavilpas** [comment]
The same error message seems to appear here, maybe something like this can help you https://github.com/neovim/neovim/issues/13893

**Comment by Daydreamer-riri** [comment]
‌‌Thank you very much for your prompt reply! Indeed, that's the reason. I simply set the shell without making the relevant settings. Thank you!

**Comment by Daydreamer-riri** [comment]
HI @mikavilpas , 抱歉再次打扰。我尝试更换使用 nushell 中使用 yazi.nvim，得到了这样的报错： 

![image](https://github.com/user-attachments/assets/cecf78cd-5455-47f3-8416-632750ab8747)

**Comment by mikavilpas** [comment]
Hmm, I have received reports from nushell users saying the plugin does work. Maybe you have to enable these for now (ref. https://github.com/mikavilpas/yazi.nvim/issues/130#issuecomment-2241063898)

```lua
    -- enable these if you are using the latest version of yazi
    -- use_ya_for_events_reading = true,
    -- use_yazi_client_id_flag = true,
```

See the readme for where you should put these: https://github.com/mikavilpas/yazi.nvim?tab=readme-ov-file#using-lazynvim

I will make these the default option in some time, but for now you need to enable them manually.

**Comment by Daydreamer-riri** [comment]
I have enabled it. You can see my configuration here:
nushell: https://github.com/Daydreamer-riri/LazyVimConfig/blob/main/lua/config/options.lua#L6-L14
yazi: https://github.com/Daydreamer-riri/LazyVimConfig/blob/main/lua/plugins/yazi.lua#L32-L33

**Comment by Daydreamer-riri** [comment]
https://github.com/neovim/neovim/issues/19648#issuecomment-1212295560
When I made the changes according to the instructions here, I got a different error:
```
Error:   × Invalid literal
   ╭─[source:1:9]
 1 │ yazi "D:\Users\ding.zhao\workspace\rn_dingzhi" --local-events "rename,delete,trash,move,cd" --chooser-file "D:\Users\DING~1.ZHA\AppData\Local\Temp\nvim.0\M3x4bW\0" > "D:\Users\DING~1.
ZHA\AppData\Local\Temp\nvim.0\M3x4bW\1"
   ·         ───────────────────┬──────────────────
   ·                            ╰── unrecognized escape after '\' in string
   ╰────


[Process exited 1]
```

**Comment by mikavilpas** [comment]
Hmm to be honest I have no idea what could be wrong with your setup. I'm not familiar with how neovim works on windows at all.

Does the same command work for you without neovim? Maybe neovim thinks it should use `\` characters as file separators since you are on windows, but they are not understood by nushell...

**Comment by Daydreamer-riri** [comment]
Hi @mikavilpas, I dug into this again (since I use nushell more frequently and have to wait almost a second to open yazi.nvim in powershell, I wanted to try nushell), and I found out that the reason yazi.nvim is not available in nushell is this: https://github.com/ nushell/nushell/issues/8174, i.e. “backslash in double quotes” in “path\to\file” is treated as an escape character. Is there any way to fix this?

**Comment by mikavilpas** [comment]
Hmm I'm not sure what the problem could be. If I try to replicate the issue with e reproduction setup described [here](https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md) (on osx) using the following command, I have no trouble opening yazi and then opening a file.

`SHELL=nu nvim -u repro.lua`

Can you try and see if you have the same behaviour?

**Comment by Daydreamer-riri** [comment]
OSX work fine because it's dir separator is ’/’, but windows's dir separator is ’\’. So you can see that error from my previous reply.

**Comment by Daydreamer-riri** [comment]
I can't test it yet because my personal computer is arm windows and can't install nvim. Next week I will try to change YAZI.nvim locally on my work computer to see if it works properly.

**Comment by mikavilpas** [comment]
I suspect it might be related to neovim somehow. It might also be that in this plugin, the library plenary.nvim is used that might not support nushell like paths yet.

**Comment by Daydreamer-riri** [comment]
https://github.com/mikavilpas/yazi.nvim/blob/main/lua%2Fyazi%2Fprocess%2Fya_process.lua#L58-L58

I see this function using this: shellescape, according to the documentation I set [shellslash](https://neovim.io/doc/user/options.html#'shellslash') to `true`, and then yazi.nvim can be opened normally. I'm not sure if there will be other questions, and I'll report it if there is.

Thank you for always following this issue!

**Comment by mikavilpas** [comment]
Wow that's really resourceful. Did not know such a setting exists, but glad it works!

**Comment by Daydreamer-riri** [comment]
Hi @mikavilpas, this setting I use breaks some other plugins. I ended up making this modification:

<img width="604" alt="{6FF75C79-5B47-44F4-BE0E-9091EED24B0D}" src="https://github.com/user-attachments/assets/1f21ad9d-7001-47cb-8f99-efc30d112a8b">

Do you mind if I submit a PR for running yazi.nvim in windows nushell to have this behavior? Maybe as a configuration item, I'm not sure what form this should take.

If you don't think this is appropriate, I can keep it in my personal fork.

**Comment by mikavilpas** [comment]
Hmm I'm glad it worked for you. I suspect something is not right in Neovim itself possibly, as I have seen neo-tree also has pretty complicated logic for escaping paths.

Let's keep it on your form for now. I think this will never change, but if this starts to come up more I can maybe add a configuration option for it in the future.

**Comment by Daydreamer-riri** [comment]
> Hmm I'm glad it worked for you. I suspect something is not right in Neovim itself possibly, as I have seen neo-tree also has pretty complicated logic for escaping paths.
> 
> Let's keep it on your form for now. I think this will never change, but if this starts to come up more I can maybe add a configuration option for it in the future.

Sure, thanks for your work!

**Comment by shouyierban** [comment]
> https://github.com/mikavilpas/yazi.nvim/blob/main/lua%2Fyazi%2Fprocess%2Fya_process.lua#L58-L58
> 
> I see this function: shellescape, according to the documentation I set [shellslash](https://neovim.io/doc/user/options.html#'shellslash') to `true`, and then yazi.nvim can be opened normally in nushell. I'm not sure if there will be other questions, and I'll report it if there is.
> 
> Thank you for always following this issue!

hi, have you found a solution? I encountered the same problem when using rustacenvim ( a rust plugin). Even setting shellslash to true, it still did not work.
![image](https://github.com/user-attachments/assets/f0accc56-ba2d-4aa2-b156-f98754a10a7c)

**Comment by Daydreamer-riri** [comment]
Hi @shouyierban, As I said [earlier](https://github.com/mikavilpas/yazi.nvim/issues/366#issuecomment-2339513992), I created a fork, made changes, and utilized bots to periodically update the upstream code.

**Comment by shouyierban** [comment]
> Hi @shouyierban, As I said [earlier](https://github.com/mikavilpas/yazi.nvim/issues/366#issuecomment-2339513992), I created a fork, made changes, and utilized bots to periodically update the upstream code.

thank you for your reply, I will try too..

**Comment by RicardoRyn** [comment]
> Hi [@mikavilpas](https://github.com/mikavilpas), this setting I use breaks some other plugins. I ended up making this modification:您好，这个设置我用的时候会破坏一些其他插件。我最终做了这个修改：
> 
> <img alt="{6FF75C79-5B47-44F4-BE0E-9091EED24B0D}" width="604" src="https://private-user-images.githubusercontent.com/70067449/365875929-1f21ad9d-7001-47cb-8f99-efc30d112a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2MTEyOTEsIm5iZiI6MTc0MTYxMDk5MSwicGF0aCI6Ii83MDA2NzQ0OS8zNjU4NzU5MjktMWYyMWFkOWQtNzAwMS00N2NiLThmOTktZWZjMzBkMTEyYThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEwVDEyNDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOThjNzNiMGFjMjA2YTFjNWVhZWM4OWUzN2JkMGYyZmQyNDQyYWQ4NDNkZTYyYjUzOTAxNTAyZTY1NTRkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I5Yg7bk3yt3m5PxOpTRsKidomvGTN3_kYv4tJPQFuSs">
> Do you mind if I submit a PR for running yazi.nvim in windows nushell to have this behavior? Maybe as a configuration item, I'm not sure what form this should take.您介意我提交一个 PR，以便在 Windows nushell 中运行 yazi.nvim 并实现这种行为吗？也许作为一个配置项，我不确定这个形式应该是什么。
> 
> If you don't think this is appropriate, I can keep it in my personal fork.如果您认为这不合适，我可以将其保留在我的个人分支中。

Yes, it works. You save my life. 👍👍👍

**Comment by mikavilpas** [comment]
I just added an option to customize how paths are escaped in case you want to try it out. It might be possible to have nushell specific path escaping as a config option now - let me know if something works for you and I can make it more obvious for nushell users. #1099
