### ISSUE TITLE
Could not find a background color, not highlighting

### ISSUE THREAD

**Issue by Muhammad95959** [mikavilpas/yazi.nvim#392]
I have a transparent background for my neovim theme and because of it I got `Could not find a background color, not highlighting` error
I don't get that with a solid background
![image](https://github.com/user-attachments/assets/a5a2328f-ab56-4fd0-a63b-de61af743217)
![image](https://github.com/user-attachments/assets/b09e37eb-4c57-4091-b6c6-72a7c1f9214e)

**Comment by mikavilpas** [comment]
Hmm, interesting. What theme do you use? What background color settings do you have?

**Comment by Muhammad95959** [comment]
> Hmm, interesting. What theme do you use? What background color settings do you have?

I found what's causing the bug
highlight_hovered_buffers_in_same_directory = true
everything is fine now after switching it to false

and as for your questions I use tokyonight theme and "xiyaowong/transparent.nvim" plugin to toggle transparency

**Comment by mikavilpas** [comment]
Ah, I see. I had not thought this case would be possible, so the error was needlessly shown. Your workaround is good, although you might still get an error message if you hover over a file you have open and visible.

I will release a fix for this behaviour (just hiding the message for now), so you should not see it after that.
