### ISSUE TITLE
error deleting associated buffer when file is deleted from yazi.nvim 

### ISSUE THREAD

**Issue by MagicDuck** [mikavilpas/yazi.nvim#397]
hi there, thank you for your awesome work! 😄
I finally switched to `yazi.nvim` from `telescope-file-broweser` and it's absolutely outstanding.
I've encountered one minor issue when deleting files from yazi, that have associated buffers opened, where the buffer has been edited without writing:
```
E89: No write since last change for buffer 166 (add ! to override)
Error executing vim.schedule lua callback: ...azi.nvim/lua/yazi/event_handling/yazi_event_handling.lua:37: Failed to unload buffer.
stack traceback:
        [C]: in function 'nvim_buf_delete'
        ...azi.nvim/lua/yazi/event_handling/yazi_event_handling.lua:37: in function <...azi.nvim/lua/yazi/event_handling/yazi_event_handling.lua:36>
Press ENTER or type command to continue
```  
Not a blocker, probably just a matter of force removing the buffer. I can take a look as well if I get some free time, but filing this one as a reminder / if somebody else can get to it first.

**Comment by mikavilpas** [comment]
Hi, and welcome on board 😄

This issue is something I think I tried to be a little too smart about. I'll add force deleting so that this can be avoided.

**Comment by MagicDuck** [comment]
awesome, thanks @mikavilpas ! 🙇
