### ISSUE TITLE
What is "ya"? How do I install it? I can't find it anywhere

### ISSUE THREAD

**Issue by tiberiuichim** [mikavilpas/yazi.nvim#401]
I get this error in `:checkhealth yazi`:

```
ERROR ya is not found on PATH. Please install ya.
```

Except I can't find anything about ya on the yazi website.

**Comment by mikavilpas** [comment]
How did you install yazi? You can install the newest version here https://github.com/sxyazi/yazi/releases

It will include `ya`, which is a command line utility that's bundled with yazi. It's required.

**Comment by tiberiuichim** [comment]
@mikavilpas I used the snap download, then installed like so (not, commands are inverted, I was retracing my history):

![image](https://github.com/user-attachments/assets/0c571960-4845-4ac0-aee8-1b4da378ec6b)

I see that ya is available in `/snap/yazi/current`, but it's not linked to in any $PATH directory.

**Comment by tiberiuichim** [comment]
I linked `ya` in `/snap/bin`, all good now.
