### ISSUE TITLE
Can I specify starting directory?

### ISSUE THREAD

**Issue by Jaehaks** [mikavilpas/yazi.nvim#425]
Thank you for your efforts,

First, when I open using `:Yazi` , it detect some wrong path. 
![image](https://github.com/user-attachments/assets/a06a1ca1-cc73-4961-bfe7-7f091c11f91c)

Can I set starting directory with this command?

**Comment by mikavilpas** [comment]
Hi! I think you might be able to. I haven't come across this issue myself, but if you use the lua api `require("yazi").yazi(config, input_path)` you can override any values for this specific invocation.

The current directory is not customized by this plugin, so I would guess it comes from neovim itself.

**Comment by Jaehaks** [comment]
@mikavilpas 
It works, thanks:)

I found what the problem about duplicated paths is, I set `shellslash = true` because neovim set / or \ as path delimiter confusingly. 
I restore the option and it works well.

**Comment by mikavilpas** [comment]
Nice. Glad you got it resolved 👍🏻
