### ISSUE TITLE
Can I disable single quote(') default shortcut?

### ISSUE THREAD

**Issue by Jaehaks** [mikavilpas/yazi.nvim#426]
Thank you for your efforts

I have indenpendent yazi's config and it has keymaps about bookmarks. check bookmark list is assigned to (')
When I push single quote(') key, it shows bookmark list but cwd is changed to parent directory also.
The bookmarks works after I push marked key (a or b etc..) but it is confused to change current displayed directory to parent folder. 

Is it normal?
1) open yazi.nvim
![image](https://github.com/user-attachments/assets/6ec60751-c3f5-449f-82aa-4e9c9026d8a1)
2) enter single quote(') to see bookmark list, it change current displayed directory 
![image](https://github.com/user-attachments/assets/f4028775-a62e-4d28-af95-38ec45c90525)
![image](https://github.com/user-attachments/assets/df419adf-0f32-4bdb-a058-e7ca9350f6e7)

**Comment by mikavilpas** [comment]
Hi, it seems like you may have some keymapping for the quote key `'` in nvim, and it triggers in the yazi floating window (which shows yazi in a neovim terminal buffer). Am I correct in assuming you don't get the same behaviour in yazi on the command line (when you run yazi outside of neovim)?

- if you get this behaviour in yazi itself, you should check the keymaps in yazi, or perhaps contact the author of this specific plugin. I don't use it myself, but I understand it's quite popular.
- on the other hand if this only happens in neovim with yazi.nvim, you could either
  - make the keymap do nothing in `"yazi"` filetypes (set [here](https://github.com/mikavilpas/yazi.nvim/blob/fc59e7b83323ab2ce70305a00819b0f76d6611b5/lua/yazi/window.lua?plain=1#L97))
  - remove the mapping in yazi buffers specifically with `config.hooks.yazi_opened = function(preselected_path, yazi_buffer_id, config)`, by defining that function and removing the keymap. It will be executed each time yazi is opened.

**Comment by Jaehaks** [comment]
@mikavilpas 
you are right. it is because nvim has default key for single quote. 
single quote(') assigned 'go to mark'  as default mapping in neovim. 

I try to delete or change the default setting of single quote in `yazi_opened`. but it doesn't work. 

in yazi, single quote works well without going to parent directory.
After I change the keymap 'go to marks' to '=',   '=' works properly in yazi.nvim

Thanks
