### ISSUE TITLE
When the session is restored, yazi will also be opened automatically

### ISSUE THREAD

**Issue by mingo99** [mikavilpas/yazi.nvim#440]
### Version
- Neovim: 0.10.1
- LazyVim: latest
- Yazi: 0.3.3

### Description
After opening the folder to restore the session(there are already files open), Yazi opens automatically.
![image](https://github.com/user-attachments/assets/8e54eb28-0aa4-47db-a550-8c024b802f48)

### Steps To Reproduce
Enter the folder where the session has been saved, enter `nvim`, and then reload the session.

### Expected Behavior
Like neo-tree, when the session already has files open, don't open yazi.

### My config
```lua
  {
    "mikavilpas/yazi.nvim",
    event = "VeryLazy",
    opts = {
      open_for_directories = true,
    },
  },
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = {
      filesystem = {
        hijack_netrw_behavior = "disabled",
      },
    },
  },
```

**Comment by mikavilpas** [comment]
I'm not familiar with this feature. I use lazyvim and it saves the session automatically (I think). I can reload the session with `s` on the start screen.

How do you reload your session exactly?

**Comment by mingo99** [comment]
Just like you.

**Comment by qeisar** [comment]
I am having something that might be similar or related. When I navigate with yazi.nvim then quit with `q`  while hovering on a directory, then try to resume with `<C-up>` yazi-nvim enters that directory.

**Comment by mingo99** [comment]
> I am having something that might be similar or related. When I navigate with yazi.nvim then quit with `q` while hovering on a directory, then try to resume with `<C-up>` yazi-nvim enters that directory.

Uh, I don't get it.

**Comment by mikavilpas** [comment]
> I am having something that might be similar or related. When I navigate with yazi.nvim then quit with `q` while hovering on a directory, then try to resume with `<C-up>` yazi-nvim enters that directory.

This happened to me too, and I opened this issue to investigate it https://github.com/sxyazi/yazi/issues/1610. Right now yazi does not seem to have a way to open and hover a directory.

**Comment by mingo99** [comment]
> I am having something that might be similar or related. When I navigate with yazi.nvim then quit with `q` while hovering on a directory, then try to resume with `<C-up>` yazi-nvim enters that directory.

Yeah, I understand what you mean, and I tried it. It's the same for me, but I think it's different from my issue. My issue seems more like `Yazi cwd` was executed directly after loading the session. BTW, maybe I missed an important detail, the situation I mentioned happens after Yazi has been opened in Neovim.

**Comment by mikavilpas** [comment]
Yeah I think that case is different. Is there some way I can reproduce this?

**Comment by mingo99** [comment]
Yeah, You can try it this way (with config above).
```shell
cd ~/.config/yazi  # Any dir
nvim .
# Yazi open automatically and select any file to open, then exit neovim (<leader>qq in Lazyvim).
nvim
```
Then you'll see it as shown in the screenshot above.

**Comment by mikavilpas** [comment]
When I open nvim the second time, it does not open any files - it shows the lazyvim default startup screen. Do you have some setting or other plugin that might do something here?

**Comment by mingo99** [comment]
Oh, sorry，I forgot a step，enter the  startup and press  s to reload  session, then  it will appear.在 2024年9月8日，14:40，Mika Vilpas ***@***.***> 写道：﻿
When I open nvim the second time, it does not open any files - it shows the lazyvim default startup screen. Do you have some setting or other plugin that might do something here?

**Comment by mikavilpas** [comment]
Oh now I can reproduce it. Thanks! I'll try to figure out a good way to fix this.

**Comment by mingo99** [comment]
> Oh now I can reproduce it. Thanks! I'll try to figure out a good way to fix this.

Thanks，Looking forward to your good news.

**Comment by mikavilpas** [comment]
Should be fixed - let me know if there are any issues that remain.

Also, thanks for reporting this bug!

**Comment by mingo99** [comment]
> Should be fixed - let me know if there are any issues that remain.
> 
> 
> 
> Also, thanks for reporting this bug!

Thanks,it has been fixed.
