### ISSUE TITLE
osc 52 clipboard

### ISSUE THREAD

**Issue by caeu** [mikavilpas/yazi.nvim#441]
Yazi works with osc 52 clipboard by default, which is very useful when working in ssh. Neovim >10 also can sync osc 52 clipboad with `+` and `*` registers. It would be great if yazi.nvim can make use of osc 52. Right now, the copy functionality in yazi.nvim doesn't work for me ssh sessions.

For neovim it may require forcing it to work with osc 52, this is streight from neovim doc:
```lua
-- force system clipboard to OSC 52, see :h osc52

vim.g.clipboard = {
  name = 'OSC 52',
  copy = {
    ['+'] = require('vim.ui.clipboard.osc52').copy('+'),
    ['*'] = require('vim.ui.clipboard.osc52').copy('*'),
  },
  paste = {
    ['+'] = require('vim.ui.clipboard.osc52').paste('+'),
    ['*'] = require('vim.ui.clipboard.osc52').paste('*'),
  },
}
```

**Comment by mikavilpas** [comment]
We looked at this in another yazi.nvim issue but Neovim did not support it back then.

But now it looks like support may have been added in https://github.com/neovim/neovim/pull/29117

Can you read through that and maybe try it on nightly Neovim? From what I understand it should not be implemented on the plugin level but in Neovim itself.

**Comment by mikavilpas** [comment]
So does it work for you in nightly neovim when using yazi.nvim too?

**Comment by caeu** [comment]
Now I tried it, and yes it does!

**Comment by caeu** [comment]
Now that I've installed neovim nightly (NVIM v0.11.0-dev-911+ga2008118a) on the remote, osc52 works fine with yazi.nvim.
And still doesn't work on last week's release of neovim v0.10.2
