### ISSUE TITLE
`Please install yazi.` when running Neovim via desktop entry due to `yazi` being installed for current user

### ISSUE THREAD

**Issue by xfzv** [mikavilpas/yazi.nvim#463]
Linux user here. `yazi` is installed only for my regular user via `cargo` so `ya` and `yazi` binaries are in `$XDG_DATA_HOME/cargo/bin` directory.

When running `nvim` from my interactive shell, no issue whatsoever with `yazi.nvim` since `$XDG_DATA_HOME/cargo/bin` is in my `$PATH`. However, if I open Neovim from the desktop entry (`/usr/share/applications/nvim.desktop`), `yazi.nvim` won't open and the following message will be printed:

https://github.com/mikavilpas/yazi.nvim/blob/813b0665e6298d3fbb29b95c4546fefecff276fd/lua/yazi.lua#L20-L23

- `/usr/share/applications/nvim.desktop` content:

```
[Desktop Entry]
Name=Neovim
GenericName=Text Editor
Comment=Edit text files
TryExec=nvim
Exec=nvim %F
Terminal=true
Type=Application
Keywords=Text;editor;
Icon=nvim
Categories=Utility;TextEditor;
StartupNotify=false
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
```

Using `Exec=sh -c "PATH=/home/xfzv/.local/share/cargo/bin:$PATH kitty -e nvim"` in a local desktop entry (`$XDG_DATA_HOME/applications/nvim.desktop`) solves the problem.

Just wondering if there is a better way. I never run Neovim via the desktop entry as far as I'm concerned, but I thought this shouldn't be a problem if some users want to.

Maybe some additional checks for `ya` and `yazi` binaries availability could be implemented, or maybe adding a note in the `README`?

---

Edit: my `yazi.nvim` config just in case:

```lua
return {
  "mikavilpas/yazi.nvim",
  cmd = { "Yazi", "Yazi cwd", "Yazi toggle" },
  opts = {
    open_multiple_tabs = true,
    yazi_floating_window_border = "single",
    keymaps = {
      show_help = false,
      open_file_in_vertical_split = false,
      open_file_in_horizontal_split = false,
      open_file_in_tab = false,
      grep_in_directory = false,
      replace_in_directory = false,
      cycle_open_buffers = false,
      copy_relative_path_to_selected_files = false,
      send_to_quickfix_list = false,
    },
  },
```

**Comment by mikavilpas** [comment]
As far as I remember, there is no custom checking for path in this plugin. Do you get the same results in `:term` when using e.g. `echo $PATH`?

**Comment by mikavilpas** [comment]
If you start the `:term`, does `which yazi` find the yazi executable for you?

Are you sure `XDG_DATA_HOME` is correct? rustup does not seem to support it https://github.com/rust-lang/cargo/issues/1734

In my zsh config I only set `XDG_CONFIG_HOME` [here](https://github.com/mikavilpas/dotfiles/blob/ceccc5d57cd3885109e0597b7c7c8e0bdddcc96d/.zshrc?plain=1#L12-L13) but then again I am on osx.

This plugin uses this implementation for finding yazi:
https://github.com/mikavilpas/yazi.nvim/blob/813b0665e6298d3fbb29b95c4546fefecff276fd/lua/yazi/utils.lua?plain=1#L52-L54

My guess is your environment is somehow not set up correctly - I think neovim does not see yazi and that caused this issue.

**Comment by mikavilpas** [comment]
Ah I see, that makes sense - I think the desktop entry never extends the PATH variable so the yazi executable cannot be found.

My guess is running `:=vim.fn.executable("yazi")` without the PATH variable extension will not find it.

I agree that this is pretty surprising behaviour, but I think it's difficult to handle this in yazi.nvim. I would like managing the PATH to be the user's responsibility.
