### ISSUE TITLE
PDF Preview 

### ISSUE THREAD

**Issue by bertradio** [mikavilpas/yazi.nvim#467]
In the latest version, PDF previews do not appear in the preview pane. Also, for some reason when I preview a pdf nvim thinks it has been loaded and it show in the history.

**Comment by mikavilpas** [comment]
Can you send a screenshot of what you are seeing?

**Comment by bertradio** [comment]
![Nvim with preview](https://github.com/user-attachments/assets/d9f2db28-cf7a-4aff-81c9-0de849477a1d)

This is what I see when a pdf gets previewed. The other problem seems to have disappeared - no longer in history.

**Comment by mikavilpas** [comment]
Maybe that is ueberzug? The neovim builtin terminal (which is used to show yazi) cannot display any images.

It may be that your yazi is following this https://yazi-rs.github.io/docs/image-preview/#neovim and falling back to ueberzug. In that case, there is a workaround in the instructions that may help.

As a last resort, you could open a bug against yazi.

**Comment by bertradio** [comment]
The problem was ueberzug_offset in yazi.toml. That's what determines the placement of the image. I needed to experiment with it to get the right values. 
![Fixed](https://github.com/user-attachments/assets/8c981686-9fa8-4a3b-9b64-44140c265ce7)

**Comment by rafisics** [comment]
> The problem was ueberzug_offset in yazi.toml. That's what determines the placement of the image. I needed to experiment with it to get the right values. 

Would you mind sharing your `yazi.toml` file? 
My `~/.config/yazi/yazi.toml` has:
```
[manager]
ueberzug_offset = [2, -0.5, -0.5, -0.5] 
```
But no visible change appears.
