### ISSUE TITLE
Can't call yazi when the plugin is installed via vimplug

### ISSUE THREAD

**Issue by lucasreis1** [mikavilpas/yazi.nvim#48]
I'd like to apologize in advance because I feel like this issue is entirely my fault, as I'm still stuck on a legacy plugin manager for vim because I can't deal with porting everything to lazynvim right now. Anyway, here's how I installed the plugin:

```vim
" These two plugins are required for yazi nvim
Plug 'mikavilpas/yazi.nvim'
Plug 'nvim-lua/plenary.nvim'
```

And here's my `config.lua`

```lua
require("yazi").setup({
  keys = {
    {
      "<leader>e",
      function()
        require("yazi").yazi()
      end,
      { desc = "Open the file manager" },
    },
  },
  ---@type YaziConfig
  opts = {
    open_for_directories = false,
  },
})
```

The issue in question is that my combination key simply does not work. Any guidance is appreciated!

**Comment by mikavilpas** [comment]
Hi! Looks like your approach can work fine, but I think it maybe mixes up lazy.nvim style setup with yazi specific setup. Try this instead:

```lua
local yazi = require("yazi")

yazi.setup(
  ---@type YaziConfig
  {
    open_for_directories = false,
  }
)

vim.keymap.set("n", "<leader>e", function()
  yazi.yazi()
end, { noremap = true, silent = true, desc = "Open the file manager" })

```

If you have your lua language server setup, it should provide you with basic autocompletion, although that is of course optional:

![image](https://github.com/mikavilpas/yazi.nvim/assets/300791/179b246f-cc9f-4b16-94d0-c13934b53c0e)

**Comment by lucasreis1** [comment]
Thank you. Your solution did indeed work. I'll try setting up the language server for lua, seems like it might be useful in the future!
