### ISSUE TITLE
Feature request: Mousewheeel support

### ISSUE THREAD

**Issue by Zeioth** [mikavilpas/yazi.nvim#49]
Back in the day I implemented this in rnvimr and implementing the same feature here would be trivial.

* The only thing necessary for this to work is disabling mouse support while on the yazi.nvim window.
* And re-enabing it when leaving the window.

You can check my PR as reference:
https://github.com/kevinhwang91/rnvimr/issues/58#issuecomment-1550090411

**Comment by mikavilpas** [comment]
Thanks for the idea!

How is yazi mouse support for you without neovim? My experience has been less than optimal, but I have some trackpad and it may complicate things.

I notice your implementation had some extra logic for tmux. Does this complicate things?

**Comment by Zeioth** [comment]
@mikavilpas The main mouse feature is covered here: "Beign able to scroll with the mousewheeel".

Yazi still lack a few important mouse features I had back in ranger.

* Scroll preview with mousewheeel.
* Ability to click an item.

Personally I use a programmable keyboard with a track**ball** and this is x300 user experience for me.

**Comment by mikavilpas** [comment]
> @mikavilpas The main mouse feature is covered here: "Beign able to scroll the list with the mousewheeel".

was this supposed to include a link? I'm curious to read more but don't know where to go 🙂 

---

Anyway, I think this is a cool idea so I'll try to implement it, perhaps as optional at first so we can try it out.

**Comment by mikavilpas** [comment]
Ok there's now a "soft launch" in the main branch. You need to opt in to this feature like this https://github.com/mikavilpas/dotfiles/commit/f7aff2b88d32c86f0deb09f9f530f8230e302fb2

Let me know how it works for you.

**Comment by Zeioth** [comment]
I can confirm it works. Thank you so much for adding it so fast!! 🎉🎉

**Comment by mikavilpas** [comment]
@Zeioth much better mouse support was merged into yazi an hour or so ago https://github.com/sxyazi/yazi/pull/1038

If you're able to build from source (I use `cargo install --path yazi-fm` to do this), you might get much better mouse support. Also remember to turn off our "hacky" setting if you try it out:

```diff
diff --git a/.config/nvim/lua/plugins/my-file-manager.lua b/.config/nvim/lua/plugins/my-file-manager.lua
index bb70be8..8d278c6 100644
--- a/.config/nvim/lua/plugins/my-file-manager.lua
+++ b/.config/nvim/lua/plugins/my-file-manager.lua

@@ -27,7 +27,6 @@ return {
     ---@type YaziConfig
     opts = {
       open_for_directories = true,
-      enable_mouse_support = true,
       -- log_level = vim.log.levels.DEBUG,
       integrations = {
         grep_in_directory = function(directory)
```
