### ISSUE TITLE
Wrong offset when preview image with Überzug++

### ISSUE THREAD

**Issue by SuniRein** [mikavilpas/yazi.nvim#535]
I use Überzug++ to preview images. It works well in terminal. However, when I use it in neovim, I get a wrong image offset. It can be solved by set `ueberzug_offset`, but it will affect the preview in the terminal.

How can I make it valid only in neovim? In other words, how can I add a custom configurations for Yazi in Neovim?

**Comment by mikavilpas** [comment]
Hi! Unfortunately using a custom configuration is not possible at the moment. I don't use this feature myself and know very little about it.

If you want to look into it, you can make sure nothing else in your configuration causes issues with displaying images using the instructions in https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md

**Comment by SuniRein** [comment]
I have tried it but find nothing strange. It seems to be a bug of Überzug++. See <https://yazi-rs.github.io/docs/image-preview#neovim>.

Now I have solved it by add a custom preview in yazi. When detecting the environment is neovim, it will add a image offset.

**Comment by ipyffor** [comment]
> I have tried it but find nothing strange. It seems to be a bug of Überzug++. See https://yazi-rs.github.io/docs/image-preview#neovim.
> 
> Now I have solved it by add a custom preview in yazi. When detecting the environment is neovim, it will add a image offset.

Excuse me, how can I set the offset value, where can I refer to your configuration?

**Comment by SuniRein** [comment]
I use a custom previewer by rewrite yazi's own previewer, like [video](https://github.com/sxyazi/yazi/blob/shipped/yazi-plugin/preset/plugins/video.lua) and [image](https://github.com/sxyazi/yazi/blob/shipped/yazi-plugin/preset/plugins/image.lua).

```lua
function M:peek(job)
	local start, url = os.clock(), ya.file_cache(job)
	if not url or not fs.cha(url) then
		url = job.file.url
	end

	ya.sleep(math.max(0, rt.preview.image_delay / 1000 + start - os.clock()))
	ya.image_show(url, job.area)
	ya.preview_widgets(job, {})
end
```

In this function, you can update `job.area` to set the offset, see https://yazi-rs.github.io/docs/plugins/utils#ya.preview_widgets. If I detect the 'NEOVIM' environment, I add a offset to it.

Howerver, I think it is not elegant, and when the native previewer updated, you need to manually update it. So finally I give it up.

**Comment by ipyffor** [comment]
I think it is possible to add an environment variable to set the value of ueberzug_offset, so that it can only be modified on the machine in question without modifying the source code or configuration, because the configuration is unified, but unfortunately I am not familiar with rust.

**Comment by ipyffor** [comment]
> I think it is possible to add an environment variable to set the value of ueberzug_offset, so that it can only be modified on the machine in question without modifying the source code or configuration, because the configuration is unified, but unfortunately I am not familiar with rust.



> I use a custom previewer by rewrite yazi's own previewer, like [video](https://github.com/sxyazi/yazi/blob/shipped/yazi-plugin/preset/plugins/video.lua) and [image](https://github.com/sxyazi/yazi/blob/shipped/yazi-plugin/preset/plugins/image.lua).
> 
> function M:peek(job)
> 	local start, url = os.clock(), ya.file_cache(job)
> 	if not url or not fs.cha(url) then
> 		url = job.file.url
> 	end
> 
> 	ya.sleep(math.max(0, rt.preview.image_delay / 1000 + start - os.clock()))
> 	ya.image_show(url, job.area)
> 	ya.preview_widgets(job, {})
> end
> In this function, you can update `job.area` to set the offset, see https://yazi-rs.github.io/docs/plugins/utils#ya.preview_widgets. If I detect the 'NEOVIM' environment, I add a offset to it.
> 
> Howerver, I think it is not elegant, and when the native previewer updated, you need to manually update it. So finally I give it up.

I think it is possible to add an environment variable to set the value of ueberzug_offset, so that it can only be modified on the machine in question without modifying the source code or configuration, because the configuration is unified, but unfortunately I am not familiar with rust.

**Comment by ipyffor** [comment]
![Image](https://github.com/user-attachments/assets/f03cb2aa-d343-40d4-94c7-e7eb8479dd3d)

**Comment by Yaman-Harfoush** [comment]
Is the issue resolved now. What do you suggest I do?
