### ISSUE TITLE
Entering the yazi window, navigation breaks

### ISSUE THREAD

**Issue by raoulg** [mikavilpas/yazi.nvim#543]
I start up nvim, and enter yazi.
I can see the files, but doing jk i go up and down, but fully left aligned.

The hl keys dont work for sideways navigation, enter does not select.

yazi works fine outside nvim.

**Comment by mikavilpas** [comment]
Can you reproduce the error with these instructions? https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md

**Comment by therealyo** [comment]
I can reproduce this too with following config

`
-- You can use this file to reproduce an issue with your configuration.

---@module "yazi"
---@module "lazy"

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)
vim.g.mapleader = " "

-- install the following plugins
---@type LazySpec
local plugins = {
	{ "catppuccin/nvim", name = "catppuccin", opts = { flavour = "macchiato" } },
	{
		"mikavilpas/yazi.nvim",
		event = "VeryLazy",
		keys = {
			{
				"<leader>-",
				"<cmd>Yazi<cr>",
				desc = "Open yazi at the current file",
			},
			{
				-- Open in the current working directory
				"<leader>cw",
				"<cmd>Yazi cwd<cr>",
				desc = "Open the file manager in nvim's working directory",
			},
			{
				-- NOTE: this requires a version of yazi that includes
				-- https://github.com/sxyazi/yazi/pull/1305 from 2024-07-18
				"<leader>e",
				"<cmd>Yazi toggle<cr>",
				desc = "Resume the last yazi session",
			},
		},
		---@type YaziConfig
		opts = {
			open_for_directories = false,
			log_level = vim.log.levels.DEBUG,
		},
	},
	{
		"max397574/better-escape.nvim",
		config = function()
			require("better_escape").setup()
		end,
	}

	
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
	install = { colorscheme = { "catppuccin" } },
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
`

**Comment by therealyo** [comment]
I can reproduce this too with following config

```
-- You can use this file to reproduce an issue with your configuration.

---@module "yazi"
---@module "lazy"

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for , name in ipairs({ "config", "data", "state", "cache" }) do
vim.env[("XDG%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
vim.fn.system({
"git",
"clone",
"--filter=blob:none",
"https://github.com/folke/lazy.nvim.git",
lazypath,
})
end
vim.opt.runtimepath:prepend(lazypath)
vim.g.mapleader = " "

-- install the following plugins
---@type LazySpec
local plugins = {
{ "catppuccin/nvim", name = "catppuccin", opts = { flavour = "macchiato" } },
{
"mikavilpas/yazi.nvim",
event = "VeryLazy",
keys = {
{
"-",
"Yazi",
desc = "Open yazi at the current file",
},
{
-- Open in the current working directory
"cw",
"Yazi cwd",
desc = "Open the file manager in nvim's working directory",
},
{
-- NOTE: this requires a version of yazi that includes
-- https://github.com/sxyazi/yazi/pull/1305 from 2024-07-18
"e",
"Yazi toggle",
desc = "Resume the last yazi session",
},
},
---@type YaziConfig
opts = {
open_for_directories = false,
log_level = vim.log.levels.DEBUG,
},
},
{
"max397574/better-escape.nvim",
config = function()
require("better_escape").setup()
end,
}

}
require("lazy").setup(plugins, {
root = root .. "/plugins",
install = { colorscheme = { "catppuccin" } },
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

**Comment by therealyo** [comment]
I can reproduce this too with following config
```lua
-- You can use this file to reproduce an issue with your configuration.

---@module "yazi"
---@module "lazy"

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)
vim.g.mapleader = " "

-- install the following plugins
---@type LazySpec
local plugins = {
	{ "catppuccin/nvim", name = "catppuccin", opts = { flavour = "macchiato" } },
	{
		"mikavilpas/yazi.nvim",
		event = "VeryLazy",
		keys = {
			{
				"<leader>-",
				"<cmd>Yazi<cr>",
				desc = "Open yazi at the current file",
			},
			{
				-- Open in the current working directory
				"<leader>cw",
				"<cmd>Yazi cwd<cr>",
				desc = "Open the file manager in nvim's working directory",
			},
			{
				-- NOTE: this requires a version of yazi that includes
				-- https://github.com/sxyazi/yazi/pull/1305 from 2024-07-18
				"<leader>e",
				"<cmd>Yazi toggle<cr>",
				desc = "Resume the last yazi session",
			},
		},
		---@type YaziConfig
		opts = {
			open_for_directories = false,
			log_level = vim.log.levels.DEBUG,
		},
	},
	{
		"max397574/better-escape.nvim",
		config = function()
			require("better_escape").setup()
		end,
	}

	
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
	install = { colorscheme = { "catppuccin" } },
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here

```

**Comment by mikavilpas** [comment]
It looks like adding better-escape causes some issues. You could see e.g. https://github.com/max397574/better-escape.nvim/issues/48 and disable all/some/??? mappings when `vim.bo.filetype == "yazi"`, which is how yazi.nvim buffers should be recognizable.
