### ISSUE TITLE
Preview image has lower brightness

### ISSUE THREAD

**Issue by sohanemon** [mikavilpas/yazi.nvim#545]
I've attached a video where you can see that Yazi within Neovim has lower brightness in the preview image, while running Yazi directly (outside of Neovim) shows it at full brightness. I'd also like to disable the animation. How can I fix this?

https://github.com/user-attachments/assets/8f6223b5-700d-45c1-9645-3dc6d7dee17e

**Comment by sohanemon** [comment]
here is my `yazi.nvim` config:
```lua
{
    "mikavilpas/yazi.nvim",
    event = "VeryLazy",
    keys = {
      {
        "-",
        "<cmd>Yazi<cr>",
        desc = "Open yazi at the current file",
      },
      {
        "_",
        "<cmd>Yazi toggle<cr>",
        desc = "Resume the last yazi session",
      },
    },
    opts = {
      open_for_directories = true,
      enable_mouse_support = true,
      floating_window_scaling_factor = 1,
      yazi_floating_window_border = "none",
      keymaps = {
        show_help = "<f1>",
      },
    },
  }
  ```

**Comment by mikavilpas** [comment]
yazi.nvim does not have any code for displaying images. Are you using ueberzugpp? You might find the answer in that project's documentation.
