### ISSUE TITLE
When opening a directory, insert mode is not activated

### ISSUE THREAD

**Issue by mikavilpas** [mikavilpas/yazi.nvim#58]
When you open yazi and then highlight (hover) a directory item, and press enter to open it, a new floating window with yazi is opened.

However, this new floating window does not currently seem to start in insert mode, which means keybindings don't work.

You can currently work around this limitation by pressing `i` to enter insert mode, but a better solution should be come up with.

This was very briefly discussed in #55

**Comment by tkivela** [comment]
Tested this a bit this morning and for me it enters the insert mode, but the active window is not the yazi floating window but the window with empty buffer underneath it.
So for me it requires manually entering normal mode (with `esc`) , switching to yazi floating window and then entering insert mode.  Then it works.

I've not done much Lua/Neovim code but I think if something like this would be run after opening directory it might help:
```lua
-- Check if the current buffer's filetype is 'yazi'
local current_ft = vim.bo.filetype
if current_ft ~= 'yazi' then
    -- Iterate through available windows
    for _, win in ipairs(vim.api.nvim_list_wins()) do
        local buf = vim.api.nvim_win_get_buf(win)
        -- Check if the buffer's filetype is 'yazi'
        local win_ft = vim.api.nvim_buf_get_option(buf, 'filetype')
        if win_ft == 'yazi' then
            -- Switch to the window and enter insert mode
            vim.api.nvim_set_current_win(win)
            vim.cmd('startinsert')
            break
        end
    end
end
```
I tried to insert the code and test it with the plugin but haven't found the right place to insert it to (maybe some kind of lifecycle issue with autogroups?).

**Comment by mikavilpas** [comment]
I spent a couple of hours trying to crack this, but couldn't solve it yet.

Let's keep this open. A solution may be available later.

For now I think the best thing you can do is manually enter insert mode after opening a directory with `i`.

**Comment by mikavilpas** [comment]
@tkivela hi, I just found a workaround/fix for this. Would you have time to verify it has been solved?
If there are issues remaining, I will reopen this issue.

**Comment by tkivela** [comment]
For some reason it still starts with insert mode in [No Name] buffer like this
![image](https://github.com/mikavilpas/yazi.nvim/assets/2592409/bdff5bfe-3320-46bc-b030-1c847a7b42a8)
If I manually enter normal mode (with `Esc`) and the switch to Yazi window it works ok.

**Comment by mikavilpas** [comment]
Hmm that's super strange. I noticed for me it now works after neovim has already started. But opening a directory from the command line does not work now.

---

Can you try the following? Create a file called `repro.lua` with the following contents:

<details><summary>Details</summary>
<p>



```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)
vim.g.mapleader = ' '

-- install plugins
local plugins = {
  'folke/tokyonight.nvim',
  {
    'mikavilpas/yazi.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
    },
    event = 'VeryLazy',
    keys = {
      {
        -- 👇 choose your own keymapping
        '<leader>fy',
        function()
          require('yazi').yazi()
        end,

        { desc = 'Open the file manager' },
      },
    },
    setup = function(_, opts)
      require('yazi').setup(opts)
    end,
    ---@type YaziConfig
    opts = {
      open_for_directories = true,
    },
  },
}
require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

vim.cmd.colorscheme('tokyonight')
```

</p>
</details> 

Next, start neovim with `nvim -u repro.lua`. It will launch in a sandbox environment and install minimal packages for this session only.

In the sandbox neovim session, launch yazi and open a directory in it with `enter`. Does it stay in insert mode when the new directory is displayed for you?

**Comment by tkivela** [comment]
Yes the problem that I gave a screenshot is in the case neovim is opened from the terminal with a directory as a parameter and config option `open_for_directories = true`for the plugin.

I can try the repro.lua script tomorrow if needed.

**Comment by mikavilpas** [comment]
Ok, that sounds like I still need to work on that part 🤔

**Comment by tkivela** [comment]
Good idea using repro config file!
When launching with `nvim -u repro.lua` and starting `yazi.nvim`with the keymapping in the repro config (`<leader>fy`) the yazi window is in normal mode and stays in normal mode when entering directories. It works ok, no problems there. The parent window seems to be in `TERMINAL`mode:
![image](https://github.com/mikavilpas/yazi.nvim/assets/2592409/fda45d72-f873-4edb-833d-e3a93e104999)

With `nvim ./foodirectory -u repro.lua` it now seems to open netrw instead of Yazi which is odd. With my own config it still opens Yazi window, but the focus in on wrong window and in insert mode. I have LazyVim "distro" as a base (https://www.lazyvim.org) so the difference might be in it. I tried to disable all my custom autocommands and even all set Vim options but it didn't make a difference.

**Comment by dinomon456** [comment]
> Tested this a bit this morning and for me it enters the insert mode, but the active window is not the yazi floating window but the window with empty buffer underneath it. So for me it requires manually entering normal mode (with `esc`) , switching to yazi floating window and then entering insert mode. Then it works.
> 
> I've not done much Lua/Neovim code but I think if something like this would be run after opening directory it might help:
> 
> ```lua
> -- Check if the current buffer's filetype is 'yazi'
> local current_ft = vim.bo.filetype
> if current_ft ~= 'yazi' then
>     -- Iterate through available windows
>     for _, win in ipairs(vim.api.nvim_list_wins()) do
>         local buf = vim.api.nvim_win_get_buf(win)
>         -- Check if the buffer's filetype is 'yazi'
>         local win_ft = vim.api.nvim_buf_get_option(buf, 'filetype')
>         if win_ft == 'yazi' then
>             -- Switch to the window and enter insert mode
>             vim.api.nvim_set_current_win(win)
>             vim.cmd('startinsert')
>             break
>         end
>     end
> end
> ```
> 
> I tried to insert the code and test it with the plugin but haven't found the right place to insert it to (maybe some kind of lifecycle issue with autogroups?).

in the file lua/yazi.lua, I put this piece of code inside of the vim.schedule function and it fixed this problem for me.

**Comment by mikavilpas** [comment]
Hmm that seems like this might be some kind of tricky timing issue. @dinomon456 would you have any idea if this could be reproduced?

Can you try if you can reproduce it using the reproduction script here https://github.com/mikavilpas/yazi.nvim/blob/master/repro.lua

**Comment by dinomon456** [comment]
> Hmm that seems like this might be some kind of tricky timing issue. @dinomon456 would you have any idea if this could be reproduced?
> 
> Can you try if you can reproduce it using the reproduction script here https://github.com/mikavilpas/yazi.nvim/blob/master/repro.lua

when i use the reproduction script with options `open_for_directories = true` and `lazy = false` and open a directory with `nvim -u repro.lua directory/` I get put into insert mode in the no name buffer and I need to click on to the yazi buffer to use it.

![feh_1289311_000001_2024-06-21-055345_2544x1395_scrot](https://github.com/mikavilpas/yazi.nvim/assets/102765073/d1b4ddd8-db60-4723-b266-1d3ff668ad65)
