### ISSUE TITLE
how to open yazi when running nvim <dir>?

### ISSUE THREAD

**Issue by tryprncp** [mikavilpas/yazi.nvim#585]
I have this autocommand to open Oil.nvim on neovim startup but when i replace it with yazi, it doesn't work.

-- Open Oil.nvim on startup
vim.api.nvim_create_autocmd('VimEnter', {
  group = custom,
  pattern = '*',
  callback = function()
    if vim.fn.isdirectory(vim.fn.argv(0)) == 1 then
      vim.cmd('Yazi' .. arg)
    end
  end,
})

![image](https://github.com/user-attachments/assets/931bda11-8469-4479-8890-231e1a0bf024)

**Comment by mikavilpas** [comment]
Hi, you can try the setting that should do this. It's in the readme.

Also you need to make sure yazi.nvim is loaded at startup, otherwise it will not be available.
