### ISSUE TITLE
how to open file to the browser/firefox using yazi?

### ISSUE THREAD

**Issue by tryprncp** [mikavilpas/yazi.nvim#591]
how to open files to the browse/firefox using yazi that otherwise would be done using gx

**Comment by mikavilpas** [comment]
If I understood correctly, you want to select a file in yazi, and then open that file in your browser/firefox.

I have never configured this myself, but I think yazi can be configured to have several ways of opening files https://yazi-rs.github.io/docs/configuration/yazi/#opener

Can you see if that helps you?
