### ISSUE TITLE
Get the yazi warning `deprecated dds event` when call `cycle_open_buffers`

### ISSUE THREAD

**Issue by liuhq** [mikavilpas/yazi.nvim#622]
like below:

![image](https://github.com/user-attachments/assets/48a7d9a5-433b-4f74-be41-7b8ef4006148)

and after pressing `<tab>` nothing happens (hmmm...it will change directory in yazi as per buffer from my understanding?)

**Comment by mikavilpas** [comment]
Hi, if you have yazi 0.4.0 or later (from 2024-12-08), you can enable `future_features.ya_emit_reveal = true` in your config to get rid of that warning.

Right now it only works if you have different files open in splits in the current tab.

**Comment by liuhq** [comment]
> Hi, if you have yazi 0.4.0 or later (from 2024-12-08), you can enable `future_features.ya_emit_reveal = true` in your config to get rid of that warning.
> 
> Right now it only works if you have different files open in splits in the current tab.

ok, I get it. thx!

**Comment by iniw** [comment]
Hi! I'm running into this issue too with `yazi` at `0.4.2` and `yazi.nvim` at `7.2.1`.
The buffers aren't even cycled, the popup just shows up.

I made a local change to the `YaziProcessApi:cd` function:
```lua
---@param path string
function YaziProcessApi:cd(path)
  vim.system({ "ya", "emit-to", self.yazi_id, "cd", path }, { timeout = 1000 })
end
```
And the popup disappears but it still doesn't work 🤔

**Comment by mikavilpas** [comment]
Can you try https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md

And maybe open a new issue?
