### ISSUE TITLE
Cannot work with nu shell on Windows

### ISSUE THREAD

**Issue by ck961018** [mikavilpas/yazi.nvim#639]
I'm using LazyVim and setting shell as follow:
```
vim.g.shell = "nu"
LazyVim.terminal.setup(vim.g.shell)
```

It is functioning normally on WSL, but cannot work on Windows:
```
==============================================================================
yazi: require("yazi.health").check()

yazi ~
- Running yazi.nvim version 6.11.0
- WARNING yazi --version looks unexpected, saw Error: [31mnu::shell::file_not_found[0m
  
    [31m×[0m File not found
     ╭─[[36;1;4msource[0m:1:1]
   [2m1[0m │ nu
     · [35;1m▲[0m
     · [35;1m╰── [35;1mCould not access file '/s': 系统找不到指定的文件。 (os error 2)[0m[0m
     ╰────
  
  
- ERROR Failed to run healthcheck for "yazi" plugin. Exception:
  D:/Tool/Neovim/share/nvim/runtime/lua/vim/version.lua:174: attempt to index local 'version' (a nil value)
```
The chinese above “系统找不到指定的文件” means "The system cannot find the specified file".
As long as change the shell to ‘cmd’ or ‘pwsh’, it can work normally again.

Here is my yazi.nvim configuration:
```
"mikavilpas/yazi.nvim",                                             
event = "VeryLazy",                                                 
keys = {                                                            
    {                                                               
        "<leader>e",                                                
        "<cmd>Yazi<cr>",                                            
        desc = "Open yazi at the current file",                     
    },                                                              
    {                                                               
        "<leader>E",                                                
        "<cmd>Yazi cwd<cr>",                                        
        desc = "Open the file manager in nvim's working directory", 
    },                                                              
},                                                                  
opts = {},                                                          
```

**Comment by mikavilpas** [comment]
Hi, right now it's not known if nushell can be supported on Windows. I don't use it, and some users have had issues with it.

You might be able to find something that works by searching the issues. It's not clear to me if it can work or not, though.

**Comment by ck961018** [comment]
Thank you!
I didn't search for the closed issues before, but now I have found that issue.
And Daydreamer-riri's fork works for me.

**Comment by mikavilpas** [comment]
@RicardoRyn sorry but I don't have the resources to support that system. But some people have reported success with a community made fork - maybe it also works for you.

**Comment by mikavilpas** [comment]
Nice 👍🏻 

Do you have open_for_directories set in your config?

**Comment by RicardoRyn** [comment]
😆 yes, it works too. Thank you

**Comment by mikavilpas** [comment]
I just added an option to customize how paths are escaped in case you want to try it out. It might be possible to have nushell specific path escaping as a config option now - let me know if something works for you and I can make it more obvious for nushell users. #1099
