### ISSUE TITLE
OSC52 copy support missing

### ISSUE THREAD

**Issue by LumenYoung** [mikavilpas/yazi.nvim#64]
Hi mikavilpas,

Thanks for this great integration of Yazi into neovim, this is the best I've used so far. One additional thing comes to my mind is the remote copy function is not enabled in yazi.nvim, which means operations like copy filename in yazi is not working when we were connecting to a remote server, even ocs52 is enabled on my neovim via the plugin. I wonder if you know how to enable such osc52 support? Thanks!

Lumen.

**Comment by mikavilpas** [comment]
Hi, and thanks for the great idea! I would like to implement it maybe over the weekend (let's see 🙂 )

Do you have a recommendation how I could test this feature out? I have not used it myself in yazi.

**Comment by LumenYoung** [comment]
You mean manually test it out or setting up the test case?

For the former I think you just need to meet the following criterion 1) a terminal emulator that supports like kitty 2) use the following [osc52 plugin](https://github.com/ojroques/nvim-osc52) for neovim, which enables osc52 for all versions of neovim 3) start this neovim instance on a remote device over ssh and try to yank text to your clipboard, you will get your text if osc52 does work.

For the latter one I have not yet think of any solution yet, but I would like to do some research on that if you need help.

Additionally, yazi itself has already supported osc52, it just didn't work after being proxy-ed inside neovim's terminal. Also the toggleterm texts can also be yanked into clipboard via osc52 once it has been enabled.

**Comment by mikavilpas** [comment]
Thanks, that's exactly what I was looking for - just a high level overview of what is going on as I'm not familiar with this feature.

Looks like the yazi implementation is [here](https://github.com/sxyazi/yazi/pull/447/files#diff-71883fc89c1420802c0035f4c1a765ea3a9b8ad7923e59ccb7e4e6dfc8cf00deR128).

Do you use it with `c` and then pick one of the options in this menu?
<img width="1716" alt="image" src="https://github.com/mikavilpas/yazi.nvim/assets/300791/f98883ef-3aa6-43ca-bf08-87a568ff023b">

**Comment by mikavilpas** [comment]
An additional request: could you try the following steps to rule out yazi.nvim specifically:
- ssh to your remote machine
- open nvim
- run `:terminal` to open a terminal inside neovim (not using yazi.nvim)
- manually start `yazi` inside that terminal
- try to copy something
- verify the clipboard gets set on your local machine

**Comment by LumenYoung** [comment]
> Thanks, that's exactly what I was looking for - just a high level overview of what is going on as I'm not familiar with this feature.
> 
> Looks like the yazi implementation is [here](https://github.com/sxyazi/yazi/pull/447/files#diff-71883fc89c1420802c0035f4c1a765ea3a9b8ad7923e59ccb7e4e6dfc8cf00deR128).
> 
> Do you use it with `c` and then pick one of the options in this menu? <img alt="image" width="1716" src="https://private-user-images.githubusercontent.com/300791/327746055-f98883ef-3aa6-43ca-bf08-87a568ff023b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Mzc2NDYsIm5iZiI6MTcxNDczNzM0NiwicGF0aCI6Ii8zMDA3OTEvMzI3NzQ2MDU1LWY5ODg4M2VmLTNhYTYtNDNjYS1iZjA4LTg3YTU2OGZmMDIzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMTU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTJiY2MzN2E4MDUzZmJiMjNlMWJjMDllMzQ0MTgwYWJkYzVlODdhZjRhMTMwM2RkMjhjMTY1NGNiNDAwODc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bhmq7gvuTJHGZPjEADL5Z4Z3GrPQelNwMEXRiilRh34">

Yeah, I've being using mainly the c and pick something

**Comment by LumenYoung** [comment]
> An additional request: could you try the following steps to rule out yazi.nvim specifically:
> 
> * ssh to your remote machine
> * open nvim
> * run `:terminal` to open a terminal inside neovim (not using yazi.nvim)
> * manually start `yazi` inside that terminal
> * try to copy something
> * verify the clipboard gets set on your local machine

You are right, following the above step can't get the desired terminal output. Maybe another distinction should be noticed: the osc52 works with toggleterm in the visual mode, not in the terminal mode. So maybe that is the reason why tui app's osc52 doesn't work.

**Comment by mikavilpas** [comment]
There seems to be an extremely simple test case here https://github.com/neovim/neovim/issues/3344

`echo -e "\033]52;c;$(base64 <<< hello)\a"`

I think you would have to paste that into the remote terminal to test it out.

But it seems to me that this might not be related to this plugin. What do you think?

**Comment by LumenYoung** [comment]
> There seems to be an extremely simple test case here [neovim/neovim#3344](https://github.com/neovim/neovim/issues/3344)
> 
> `echo -e "\033]52;c;$(base64 <<< hello)\a"`
> 
> I think you would have to paste that into the remote terminal to test it out.
> 
> But it seems to me that this might not be related to this plugin. What do you think?

I've tested it out, and turns out that you can't get the hello pasted from within neovim's built terminal, suggesting that the reason behind is neovim's terminal lack osc52 support. In that case I would say this problem is not related to yazi.nvim plugin since it is an upstream problem.

Thanks for the help!

**Comment by LumenYoung** [comment]
For those who are still interested in the possibility of pasting from remote yazi.nvim, [this neovim issue](https://github.com/neovim/neovim/issues/20672) is tracking the osc52 support in terminal buffer of neovim.
