### ISSUE TITLE
Yazi loses focus on mouse click

### ISSUE THREAD

**Issue by gldtn** [mikavilpas/yazi.nvim#70]
If you click anywhere in the terminal window, even on top of yazi, it loses focus and becomes unusable. You have to kill it with `:q`  and get back into it!

**Comment by gldtn** [comment]
Yes, here is a gif

![repro](https://github.com/mikavilpas/yazi.nvim/assets/981383/6869c43d-2a79-4614-b0c7-f562e8fcd3bd)

**Comment by mikavilpas** [comment]
Thanks for the gif, it was really helpful. I think this is actually built in behaviour in neovim!

If you run a `:terminal` and do the same thing, it behaves the same. You can still continue using it if you press `i` to enter insert mode though. The same works for yazi.nvim.

**Comment by mikavilpas** [comment]
I think this might have been worked around in the latest version, in bc2aabbc23aa (included in version v1.1.3)
