### ISSUE TITLE
Parentheses in path cause error

### ISSUE THREAD

**Issue by vargasd** [mikavilpas/yazi.nvim#75]
Hey, thanks for the awesome plugin!

I noticed that [fix: not being able to open files with special chars on osx](https://github.com/mikavilpas/yazi.nvim/commit/8c5ef239f73c07e80e51cdacf55b609a4ef012ae) broke parentheses in the file path since they are not escaped by `fnameescape`. It seems like that function works for commands inside of neovim (`:e (filename)` worked fine), but since this is getting passed as a command to a terminal, it seems like more escaping may be needed.

Steps to repro:
1. `mkdir "(foo)"`
1. `touch "(foo)/bar"`
1. `nvim "(foo)/bar"`
1. Execute `:lua require('yazi').yazi()`

Error:
```
zsh:1: no matches found: /path/to/(foo)/bar

[Process exited 1]
```

Version info:
NVIM v0.9.5
Yazi 0.2.5 (Homebrew 2024-04-23)
zsh 5.9 (x86_64-apple-darwin23.0)
macOS 14.4.1 (23E224)

**Comment by mikavilpas** [comment]
Thanks for the report! We've had some challenges with special file paths recently.

I can reproduce the issue, and will try to find a good fix.
