### ISSUE TITLE
yazi_closed_successfully does not successfully trigger upon exit

### ISSUE THREAD

**Issue by chaozwn** [mikavilpas/yazi.nvim#85]
![image](https://github.com/mikavilpas/yazi.nvim/assets/51357674/933eef4d-bd34-4c7b-a9d7-562fa56c9629)

**Comment by mikavilpas** [comment]
I think I might have fixed this yesterday, and released just now. I'm not completely sure if it fixes your issue.
Can you pull in the latest changes and try it out?

**Comment by KevinW-LRL** [comment]
> I think I might have fixed this yesterday, and released just now. I'm not completely sure if it fixes your issue. Can you pull in the latest changes and try it out?

i have tested, it works well, thx.

**Comment by chaozwn** [comment]
> I think I might have fixed this yesterday, and released just now. I'm not completely sure if it fixes your issue. Can you pull in the latest changes and try it out?

fixed. closed
