### ISSUE TITLE
How to open `yazi` with current buffer file selected?

### ISSUE THREAD

**Issue by kohane27** [mikavilpas/yazi.nvim#90]
Hello! Hope you're doing well. Thank you for creating this plugin!

## Description

How to open `yazi` with current buffer file selected?

With `ranger.nvim`, there is the following API:

```lau
require("ranger-nvim").open(select_current_file: true)
```

It seems this feature is not yet existed?

Thank you!

**Comment by mikavilpas** [comment]
Hi! Yes, this can be done.

Try this:

```lua
-- will select the current file / directory by default
require("yazi").yazi()

-- you can also pass explicitly it as the second argument
require("yazi").yazi({}, "/path/to/file")
```

**Comment by kohane27** [comment]
I must be blind! Apologies for the noise and thank you for such a quick reply; I really appreciate it. Thank you again and have a good day:)

**Comment by mikavilpas** [comment]
Haha, no problem 😄
